theme: jekyll-theme-hacker
title: MongoDB Replica Set Monitoring with Grafana and Prometheus
description: MongoDB Prometheus Exporter Dashboard.
plugins:
  - jekyll-seo-tag
google_analytics: G-HKZGCJKVK1
